---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rammandal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rammandal
  template:
    metadata:
      labels:
        app: rammandal
    spec:
      containers:
        - name: rammandal
          image: rammandal/pipeline-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 80


 
 
